version: '3'
services: 

  chat:
    image: raphaelmarques84/realtime-chat-chat
    build: ./services/chat
    ports:
      - "3001:3000"
    environment:
      - DB_URL=compose-db-url
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./services/chat:/app
      - /app/node_modules
  
  user:
    image: raphaelmarques84/realtime-chat-user
    build: ./services/user
    ports:
      - "3002:3000"
    environment:
      - DB_URL=compose-db-url
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./services/user:/app
      - /app/node_modules
    command: npm run dev
  
  app: 
    image: raphaelmarques84/realtime-chat-app
    build: ./services/app
    ports:
      - "3000:3000"
    environment:
      - CHAT_URL=http://chat:3000
      - USER_URL=http://user:3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./services/app:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - chat
      - user
  
  nginx:
    image: nginx:1.17
    ports:
      - "8080:80"
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - chat
      - user
    environment:
      - APP_URL=http://app:3000
      - CHAT_URL=http://chat:3000
      - USER_URL=http://user:3000